import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { CTASection, Reveal, SectionLabel, VisualBlock } from "../components";
import { materialNotes, portfolioProjects, processSteps, services, whyAmbara } from "../data";

export function Home() {
  return (
    <main>
      <section className="relative overflow-hidden pt-24">
        <div className="mx-auto grid min-h-[92svh] max-w-7xl gap-10 px-5 pb-14 pt-12 md:grid-cols-[0.86fr_1.14fr] md:px-8 md:pb-20 md:pt-20">
          <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, ease: "easeOut" }} className="flex flex-col justify-center">
            <p className="mb-5 text-xs font-medium uppercase tracking-[0.32em] text-champagne">Custom Furniture • Interior Studio • Project-Based Craftsmanship</p>
            <h1 className="max-w-2xl font-serif text-4xl leading-[1.04] text-charcoal sm:text-5xl lg:text-6xl">Ruang yang dirancang dengan tenang, dibuat untuk bertahan.</h1>
            <p className="mt-7 max-w-xl text-base leading-8 text-graphite/72 md:text-lg">AMBARA merancang furnitur premium dan interior yang terasa lapang, tertata, dan berumur panjang. Setiap garis dibuat seperlunya, setiap material dipilih dengan sabar.</p>
            <div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link className="btn-primary" to="/portofolio">Lihat Portofolio</Link><Link className="btn-secondary" to="/lacak-proyek">Preview Lacak Proyek</Link></div>
            <div className="mt-12 grid max-w-xl grid-cols-3 border-y border-charcoal/10 py-5 text-xs uppercase tracking-[0.18em] text-graphite/60"><span>Residensial</span><span>Hospitality</span><span>Built-in</span></div>
          </motion.div>
          <motion.div initial={{ opacity: 0, scale: 0.985 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 1, ease: "easeOut", delay: 0.12 }} className="hero-visual min-h-[520px] md:min-h-[680px]">
            <div className="absolute inset-6 border border-white/45" /><div className="absolute left-[10%] top-[12%] h-[48%] w-[34%] border border-charcoal/20 bg-linen/64 backdrop-blur-sm" /><div className="absolute right-[9%] top-[16%] h-[64%] w-[34%] bg-charcoal/90" /><div className="absolute bottom-[17%] left-[16%] h-[20%] w-[64%] bg-ivory shadow-soft" /><div className="absolute bottom-[25%] left-[22%] h-px w-[50%] bg-champagne" /><div className="absolute bottom-[31%] right-[18%] h-20 w-20 rounded-full border border-champagne/70" />
            <div className="absolute bottom-5 left-5 right-5 flex items-end justify-between border-t border-charcoal/15 pt-4 text-charcoal"><span className="max-w-[13rem] text-sm leading-5">Komposisi visual ruang privat dan furnitur kustom</span><span className="text-xs uppercase tracking-[0.24em]">Jakarta</span></div>
          </motion.div>
        </div>
      </section>
      <section className="border-y border-charcoal/10 bg-linen py-20 md:py-28"><div className="content-grid"><Reveal><SectionLabel>Tentang Ambara</SectionLabel><h2 className="section-title">Studio yang menata ruang melalui proporsi, material, dan ritme hidup pemiliknya.</h2></Reveal><Reveal delay={0.08}><p className="lead-copy">Kami bekerja seperti studio arsitektur kecil: mendengar, mengukur, menyusun, lalu membuat detail yang bisa dihuni lama. Tidak berlebihan, tidak tergesa, dan tidak mengikuti tren sesaat.</p><Link className="text-link mt-8 inline-flex" to="/tentang">Mengenal AMBARA</Link></Reveal></div></section>
      <section className="section-wrap"><div className="section-heading"><div><SectionLabel>Layanan Pilihan</SectionLabel><h2 className="section-title">Panel layanan untuk ruang yang membutuhkan rasa dan presisi.</h2></div><Link className="text-link" to="/layanan">Lihat semua layanan</Link></div><div className="premium-grid mt-12">{services.slice(0, 3).map((service, index) => <Reveal key={service.title} delay={index * 0.06}><article className="service-panel"><span className="text-sm text-champagne">{service.number}</span><h3 className="mt-10 font-serif text-3xl">{service.title}</h3><p className="mt-4 leading-7 text-graphite/70">{service.summary}</p><div className="mt-8 border-t border-charcoal/10 pt-5 text-sm text-graphite/62">{service.suitable}</div></article></Reveal>)}</div></section>
      <section className="bg-charcoal py-20 text-linen md:py-28"><div className="mx-auto max-w-7xl px-5 md:px-8"><div className="section-heading"><div><SectionLabel>Portofolio Pilihan</SectionLabel><h2 className="section-title text-linen">Galeri terkurasi, tenang, dan berlapis.</h2></div><Link className="text-link text-champagne" to="/portofolio">Jelajahi portofolio</Link></div><div className="mt-12 grid gap-5 md:grid-cols-12">{portfolioProjects.slice(0, 3).map((project, index) => <Link key={project.slug} to={`/portofolio/${project.slug}`} className={`group ${index === 0 ? "md:col-span-7" : "md:col-span-5"}`}><VisualBlock tone={project.tone} tall={index === 0} /><div className="mt-5 flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.22em] text-champagne">{project.category}</p><h3 className="mt-2 font-serif text-2xl">{project.title}</h3><p className="mt-1 text-sm text-linen/55">{project.type}</p></div><p className="text-sm text-linen/55">{project.year}</p></div></Link>)}</div></div></section>
      <section className="section-wrap"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><SectionLabel>Material & Craftsmanship</SectionLabel><h2 className="section-title">Detail dibuat untuk terasa halus, bukan untuk memanggil perhatian.</h2></div><div className="grid gap-px bg-charcoal/10 sm:grid-cols-2">{materialNotes.map((item, index) => <Reveal key={item} delay={index * 0.05} className="bg-ivory p-8"><span className="text-sm text-champagne">0{index + 1}</span><h3 className="mt-12 font-serif text-2xl">{item}</h3><p className="mt-4 leading-7 text-graphite/68">Keputusan kecil yang menentukan rasa ruang: sentuhan tangan, ketebalan garis, pertemuan bidang, dan ketahanan harian.</p></Reveal>)}</div></div></section>
      <section className="bg-parchment py-20 md:py-28"><div className="mx-auto max-w-7xl px-5 md:px-8"><SectionLabel>Proses Kerja</SectionLabel><div className="grid gap-4 md:grid-cols-4">{processSteps.slice(0, 8).map((step, index) => <div key={step} className="process-chip"><span>{String(index + 1).padStart(2, "0")}</span><p>{step}</p></div>)}</div></div></section>
      <section className="section-wrap"><div className="content-grid"><div><SectionLabel>Why Ambara</SectionLabel><h2 className="section-title">Karena ruang premium membutuhkan komunikasi yang sama rapinya dengan hasil akhirnya.</h2></div><div className="space-y-4">{whyAmbara.map((item, index) => <Reveal key={item} delay={index * 0.04}><div className="reason-row"><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></div></Reveal>)}</div></div></section>
      <section className="bg-linen py-20 md:py-28"><div className="mx-auto max-w-7xl px-5 md:px-8"><SectionLabel>Testimoni</SectionLabel><div className="grid gap-6 md:grid-cols-3">{["A.P.", "R.M.", "N.S."].map((initial, index) => <figure key={initial} className="testimonial-card"><div className="initial-mark">{initial}</div><blockquote>"Prosesnya terasa tenang, rinci, dan sangat jelas. Hasil akhirnya rapi tanpa kehilangan karakter ruang."</blockquote><figcaption>{index === 0 ? "Residensial, Jakarta Selatan" : index === 1 ? "Villa privat, Bali" : "Studio komersial, Bandung"}</figcaption></figure>)}</div></div></section>
      <CTASection />
    </main>
  );
}
