export const navItems = [
  { label: "Tentang", href: "/tentang" },
  { label: "Layanan", href: "/layanan" },
  { label: "Portofolio", href: "/portofolio" },
  { label: "Proses", href: "/proses" },
  { label: "Lacak Proyek", href: "/lacak-proyek" },
  { label: "Kontak", href: "/kontak" },
];

export const services = [
  {
    number: "01",
    title: "Custom Furniture",
    slug: "custom-furniture",
    summary: "Furnitur lepas dan statement piece yang dibuat sesuai ukuran, material, dan karakter ruang.",
    suitable: "Pemilik hunian, villa, butik, dan ruang privat yang membutuhkan furnitur presisi.",
    deliverables: ["Sketsa arah desain", "Gambar produksi", "Kurasi material", "Finishing sample"],
    process: ["Brief ruang", "Proporsi dan material", "Produksi workshop", "Quality control"],
  },
  {
    number: "02",
    title: "Interior Design",
    slug: "interior-design",
    summary: "Perencanaan interior menyeluruh dengan bahasa ruang yang tenang, hangat, dan tahan lama.",
    suitable: "Residensial baru, renovasi ruang utama, suite privat, dan ruang representatif.",
    deliverables: ["Mood direction", "Layout", "Material board", "Styling direction"],
    process: ["Konsultasi", "Konsep desain", "Revisi terarah", "Finalisasi dokumen"],
  },
  {
    number: "03",
    title: "Built-in Furniture",
    slug: "built-in-furniture",
    summary: "Kabinet, wardrobe, kitchen, panel dinding, dan storage yang menyatu dengan arsitektur ruang.",
    suitable: "Ruang yang membutuhkan penyimpanan rapi tanpa mengorbankan proporsi visual.",
    deliverables: ["Pengukuran", "Shop drawing", "Material specification", "Instalasi"],
    process: ["Site survey", "Detail teknis", "Produksi", "Pemasangan"],
  },
  {
    number: "04",
    title: "Residential Projects",
    slug: "residential-projects",
    summary: "Pendampingan desain dan furnitur untuk rumah, apartemen, villa, dan kediaman privat.",
    suitable: "Klien yang ingin hunian terasa personal, rapi, dan matang sejak awal.",
    deliverables: ["Konsep ruang", "Pilihan furnitur", "Koordinasi material", "Styling akhir"],
    process: ["Mendengar kebutuhan", "Menyusun konsep", "Produksi terukur", "Serah terima"],
  },
  {
    number: "05",
    title: "Commercial Projects",
    slug: "commercial-projects",
    summary: "Interior dan furnitur untuk butik, lounge, kantor privat, hospitality, dan ruang brand.",
    suitable: "Bisnis yang membutuhkan pengalaman ruang premium dan konsisten dengan identitas brand.",
    deliverables: ["Brand spatial direction", "Furnitur kustom", "Fixture", "Installation guide"],
    process: ["Brand brief", "Konsep pengalaman", "Prototype detail", "Implementasi"],
  },
  {
    number: "06",
    title: "Space Planning",
    slug: "space-planning",
    summary: "Studi alur, proporsi, cahaya, dan fungsi agar ruang bekerja halus sebelum masuk produksi.",
    suitable: "Ruang terbatas, layout baru, renovasi bertahap, dan proyek yang butuh keputusan awal.",
    deliverables: ["Layout options", "Zoning", "Flow study", "Furniture scale guide"],
    process: ["Analisis ruang", "Alternatif layout", "Diskusi", "Arahan final"],
  },
];

export const portfolioProjects = [
  {
    slug: "residensi-senja",
    title: "Residensi Senja",
    type: "Interior residensial",
    category: "Residensial",
    year: "2026",
    location: "Jakarta Selatan",
    tone: "from-[#efe8da] via-[#c9c1b3] to-[#282723]",
    concept: "Hunian keluarga dengan ruang publik yang teduh, garis rendah, dan transisi material yang lembut.",
    materials: ["Travertine honed", "Linen ivory", "Charcoal metal", "Oak veneer ringan"],
    challenge: "Menyatukan ruang keluarga dan ruang makan agar terasa terbuka tanpa kehilangan kehangatan privat.",
    solution: "AMBARA merancang furnitur rendah, kabinet built-in tipis, dan palet material yang bergerak pelan dari ivory ke stone gray.",
  },
  {
    slug: "villa-aksara",
    title: "Villa Aksara",
    type: "Furnitur kustom",
    category: "Villa",
    year: "2025",
    location: "Bali",
    tone: "from-[#f7f2e8] via-[#bdb8ae] to-[#c8a86a]",
    concept: "Villa tropis kontemporer dengan furnitur kustom yang ringan, terukur, dan tidak menutup arsitektur.",
    materials: ["Stone gray plaster", "Brushed champagne metal", "Outdoor-grade fabric", "Natural woven detail"],
    challenge: "Menghadirkan furnitur yang kuat untuk iklim villa tanpa terasa berat secara visual.",
    solution: "Setiap modul dibuat dengan struktur tahan lembap, siluet bersih, dan aksen metal tipis untuk memberi rasa premium.",
  },
  {
    slug: "studio-nara",
    title: "Studio Nara",
    type: "Commercial studio",
    category: "Komersial",
    year: "2025",
    location: "Bandung",
    tone: "from-[#e9e1d3] via-[#f9f6ef] to-[#171717]",
    concept: "Ruang konsultasi dan display yang terasa seperti galeri kecil, bukan showroom yang ramai.",
    materials: ["Matte plaster", "Blackened steel", "Textured glass", "Champagne trim"],
    challenge: "Membuat ruang komersial tetap fungsional, tetapi memiliki keheningan seperti studio desain privat.",
    solution: "Layout dibuat bertahap: area penerima, meja konsultasi, display material, dan ruang diskusi yang saling terhubung.",
  },
  {
    slug: "suite-dharma",
    title: "Suite Dharma",
    type: "Kurasi interior",
    category: "Hospitality",
    year: "2024",
    location: "Yogyakarta",
    tone: "from-[#fbf8f0] via-[#d7d0c2] to-[#77736a]",
    concept: "Suite tenang dengan layer tekstur tipis, pencahayaan rendah, dan furnitur berproporsi hotel butik.",
    materials: ["Boucle fabric", "Warm ivory wall", "Smoked mirror", "Soft stone top"],
    challenge: "Mengubah suite compact agar terasa luas, hangat, dan tetap mudah dirawat.",
    solution: "AMBARA memilih storage tertanam, meja melayang, dan pencahayaan indirect untuk menjaga ruang tetap ringan.",
  },
  {
    slug: "rumah-ambar",
    title: "Rumah Ambar",
    type: "Built-in furniture",
    category: "Residensial",
    year: "2024",
    location: "Surabaya",
    tone: "from-[#e4ded3] via-[#bdb8ae] to-[#2b2a27]",
    concept: "Rumah urban dengan storage tertutup, garis kabinet rapi, dan ruang utama yang tidak terasa penuh.",
    materials: ["Lacquer matte", "Stone laminate", "Linen panel", "Slim black handle"],
    challenge: "Menyimpan banyak kebutuhan keluarga tanpa membuat ruang tampak padat.",
    solution: "Kami membuat sistem built-in dari foyer sampai pantry dengan ritme garis yang konsisten.",
  },
];

export const processSteps = [
  "Konsultasi",
  "Pengukuran",
  "Konsep Desain",
  "Revisi",
  "Persetujuan",
  "Produksi",
  "Finishing",
  "Pengiriman",
  "Instalasi",
  "Serah Terima",
];

export const trackingStages = [
  "Konsultasi",
  "Konsep Desain",
  "Revisi",
  "Persetujuan",
  "Produksi",
  "Finishing",
  "Pengiriman",
  "Instalasi",
  "Selesai",
];

export const materialNotes = [
  "Kurasi material",
  "Detail finishing",
  "Harmoni ruang",
  "Konstruksi tahan lama",
];

export const whyAmbara = [
  "Desain personal sesuai ruang",
  "Produksi terukur",
  "Material terkurasi",
  "Komunikasi proyek yang jelas",
  "Hasil akhir rapi dan tahan lama",
];
